### ISSUE TITLE
Add llhd-sim execution and output

### ISSUE THREAD

**Issue by fabianschuiki** [llhd-org/www.llhd.io#2]
Add the option to not only compile HDL to LLHD, but also run the generated assembly in llhd-sim. The resulting VCD should be converted to an SVG (limited max number of signals and time steps) and returned to the browser. This adds an `execute` request to the server, which needs to be handled differently than `compile`.

### Todo
- [ ] Add llhd-sim to the Dockerfile
- [ ] Add `execute` query and corresponding call to `llhd-sim`
- [ ] Add VCD-to-SVG rendering either in the container or in the webserver
- [ ] Add button on website to switch between `Compile` and `Execute` (maybe rather `LLHD` and `Waveform`)
